[package]
name = "candle-neat"
description = "A library that uses candle-rs under the hood for training/testing NEAT"
repository = "https://github.com/dsgallups/candle-neat"
readme = "README.md"
rust-version = "1.80"
authors = ["Daniel Gallups <dsgallups@protonmail.com>"]
keywords = [
    "genetic_algorithms",
    "neural_networks",
    "neuroevolution",
    "network_topologies",
    "speciation",
]
categories = ["algorithms", "science", "simulation"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
default-run = "candle_sandbox"

[[bin]]
name = "candle_sandbox"

[[bin]]
name = "lib_sandbox"


[features]
crossover = ["genetic-rs/crossover"]
max-index = []


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-big-array = { version = "0.5.1" }
bitflags = "2.6.0"
candle-core = { version = "0.6.0" }
genetic-rs = { version = "0.5.3", features = ["derive"] }
rand = "0.8.5"
rayon = { version = "1.10.0" }
# nalgebra = "0.33.0"


[dev-dependencies]
bincode = "1.3.3"
serde_json = "1.0"
