[package]
name = "candle-neat"
description = "A library that uses candle-rs under the hood for training/testing NEAT"
repository = "https://github.com/dsgallups/candle-neat"
readme = "README.md"
rust-version = "1.80"
authors = ["Daniel Gallups <dsgallups@protonmail.com>"]
keywords = [
    "genetic_algorithms",
    "neural_networks",
    "neuroevolution",
    "network_topologies",
    "speciation",
]
categories = ["algorithms", "science", "simulation"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"


[features]


[dependencies]
bitflags = "2.6.0"
genetic-rs = "0.5.3"
lazy_static = "1.5.0"
rand = "0.8.5"
rayon = "1.10.0"

[dev-dependencies]
